library(dplyr)
MechaCar <- read.csv('MechaCar_mpg.csv')
regg <- lm(mpg ~ AWD + ground_clearance + spoiler_angle +vehicle_weight + vehicle_length,data=MechaCar)
summary(regg)
Sus_Coil <- read.csv('Suspension_Coil.csv')
total_summary <- summarize(Sus_Coil, Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
lot_summary <- Sus_Coil %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
t.test(Sus_Coil$PSI, mu=1500)
lot_1 <- subset(Sus_Coil, Manufacturing_Lot == 'Lot1')
lot_2 <- subset(Sus_Coil, Manufacturing_Lot == 'Lot2')
lot_3 <- subset(Sus_Coil, Manufacturing_Lot == 'Lot3')

t.test(lot_1$PSI,mu=1500)
t.test(lot_2$PSI,mu=1500)
t.test(lot_3$PSI,mu=1500)
